AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  This SAM template contains the basic structure to build the resources of the SAM Typescript DOJO.

Globals:
  Function:
    Timeout: 20
    Runtime: nodejs16.x
    Architectures:
      - arm64

Resources:
  GetVehicleLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambdas/getVehicleLambda
      Handler: app.handler

  AWSAppSyncServiceRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - appsync.amazonaws.com
              Action:
                - sts:AssumeRole
        Path: /

  RoleAppSyncCloudWatch:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSAppSyncPushToCloudWatchLogs"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - appsync.amazonaws.com

  LambdaAccessPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: lambda-access
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'lambda:invokeFunction'
            Resource:
              - !GetAtt GetVehicleLambda.Arn
      Roles:
        - Ref: AWSAppSyncServiceRole

  TypescriptAPI:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      Name:
        Fn::Sub: "Typescript-API-${AWS::StackName}"
      AuthenticationType: API_KEY
      LogConfig:
        CloudWatchLogsRoleArn: !GetAtt RoleAppSyncCloudWatch.Arn
        ExcludeVerboseContent: FALSE
        FieldLogLevel: ALL

  TypescriptAPIApiKey:
    Type: AWS::AppSync::ApiKey
    Properties:
      ApiId: !GetAtt TypescriptAPI.ApiId
      Description: API Key with restricted access for Typescript AppSync API version
      Expires: 1665163864 # Thursday, July 21, 2050 10:15:07 PM
    DependsOn: TypescriptAPI

  TypescriptAPISchema:
    Type: AWS::AppSync::GraphQLSchema
    Properties:
      ApiId: !GetAtt TypescriptAPI.ApiId
      DefinitionS3Location: ./src/appsync/schema.graphql

  GetVehicleLambdaDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt TypescriptAPI.ApiId
      Name: GetVehicleLambda
      Type: AWS_LAMBDA
      ServiceRoleArn: !GetAtt AWSAppSyncServiceRole.Arn
      LambdaConfig:
        LambdaFunctionArn: !GetAtt GetVehicleLambda.Arn

  GetVehicleResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt TypescriptAPI.ApiId
      TypeName: Query
      FieldName: getVehicle
      DataSourceName: !GetAtt GetVehicleLambdaDataSource.Name
      RequestMappingTemplateS3Location: ./src/appsync/mappings/Query.getVehicle.req.vtl
      ResponseMappingTemplateS3Location: ./src/appsync/mappings/Query.getVehicle.res.vtl
    DependsOn: TypescriptAPISchema

Outputs:
  ApiUrl:
    Description: "Typescript AppSync API URL"
    Value: !GetAtt TypescriptAPI.GraphQLUrl
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-GraphQLApiUrl"
